server {
    listen 80;
    server_name _;
    resolver 8.8.8.8 ipv6=off valid=30s;
    proxy_buffer_size 16k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 24k;

    root /usr/share/nginx/html;
    index index.html;

    location /auth/ {
        proxy_pass ${AUTH_SERVICE_URL}/auth/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_next_upstream off;
    }

    location /accounts/ {
        proxy_pass ${BANKING_SERVICE_URL}/accounts/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "close";
        proxy_next_upstream off;
    }

    location /transfers {
        proxy_pass ${BANKING_SERVICE_URL}/transfers;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "close";
        proxy_next_upstream off;
    }

    location /admin/nodes/ {
        proxy_pass ${OBS_SERVICE_URL}/admin/nodes/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 180s;
        proxy_next_upstream off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
