upstream auth_service_local {
    server authentication-service:8080;
}

upstream banking_service_local {
    server banking-service:8080;
}

upstream observability_service_local {
    server observability-service:8080;
}

server {
    listen 80;
    server_name _;

    location /auth/ {
        proxy_pass http://auth_service_local;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /accounts/ {
        proxy_pass http://banking_service_local;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /transfers {
        proxy_pass http://banking_service_local;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/nodes/ {
        proxy_pass http://observability_service_local;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /health {
        proxy_pass http://banking_service_local;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
